fd-auth-server:
  esSigPrivKeyConfig:
    fileName: keys/ref-privkey.pem
    keyId: puk_fd_sig
    use: sig
    addX5c: false
  esSigPubKeyConfig:
    fileName: keys/ref-pubkey.pem
    keyId: puk_fd_sig
    use: sig
  tlsClientPrivKeyConfig:
    fileName: classpath:cert/ref-key.p12
    keyId: puk_tls_sig
    use: sig
    x5cInJwks: true
  encPrivKeyConfig:
    fileName: keys/ref-privkey.pem
    keyId: puk_fd_enc
    use: enc
    x5cInJwks: false
  encPubKeyConfig:
    fileName: keys/ref-pubkey.pem
    keyId: puk_fd_enc
    use: enc
  tokenSigPrivKeyConfig:
    fileName: keys/ref-privkey.pem
    keyId: puk_token_sig
    use: sig
    x5cInJwks: false
  tokenSigPubKeyConfig:
    fileName: keys/ref-pubkey.pem
    keyId: puk_token_sig
    use: sig
  symmetricEncryptionKey: "setYourKeyHere"
  serverUrl: "${FD_AUTH_SERVER_URL:http://set-address-here}"
  fedmasterUrl: "${FEDMASTER_SERVER_URL:http://set-address-here}"
  fedmasterSigPubKeyFilePath: "keys/ref-fedmaster-sig-pubkey.pem"
  debug:
    requestLogging: true
  loglevel: debug
server:
  port: ${SERVER_PORT:8084}
management:
  server:
    port: ${MANAGEMENT_PORT:8184}
  endpoints:
    web:
      exposure:
        include: "health"
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true
    logfile:
      enabled: true
